### PR TITLE
First commit in Antons branch

### PR DESCRIPTION
**Pull request by AChernetskyy**
Any comments?

### CODE REVIEW

**Comment by AChernetskyy** [comment]
Comments

**Comment by yonashaile12** [comment]
i like your codes keep it up

**Comment by AChernetskyy** [comment]
ok, see it, where is the conflict?

**Comment by AChernetskyy** [comment]
How do we resolve it?

**Comment by Abasiyanik** [comment]
i like thes codes

**Comment by yonashaile12** [comment]
i think you need to checkout master

**Comment by yonashaile12** [comment]
ignore the changes

**Comment by yonashaile12** [comment]
i think you have merged all the changes

**Pull request closed without merging**
